# Generated by Django 4.1.7 on 2023-03-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=255, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Task', 'задача'), ('Bug', 'ошибка'), ('Enhancement', 'улучшение')], max_length=255, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=300, verbose_name='описание')),
                ('description', models.TextField(max_length=2000, verbose_name='полное_описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время_создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время_обновления')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tasks', to='webapp.status', verbose_name='статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tasks', to='webapp.type', verbose_name='тип')),
            ],
        ),
    ]
